import type { FAQItem } from './countries';

export const COUNTRY_FAQS: Record<string, FAQItem[]> = {
	sweden: [
		{ question: 'Where can I read Swedish news in English?', answer: 'Nordics Today provides daily Swedish news in English, covering Riksdag parliament, Stockholm business, Volvo industry, and cultural events for expats and global readers.' },
		{ question: 'What is the best English news site for Sweden?', answer: 'Nordics Today is a comprehensive English news aggregator for Sweden, offering real-time coverage of Swedish politics, business, technology, and society from Stockholm, Gothenburg, and Malmö.' },
		{ question: 'Does Sweden have English newspapers?', answer: 'While most Swedish newspapers publish in Swedish, Nordics Today provides Swedish news in English, making it accessible for expats, international residents, and English speakers worldwide.' },
		{ question: 'How can expats follow Swedish politics in English?', answer: 'Nordics Today covers Swedish political news in English, including Riksdag debates, government policy changes, and election updates, making it easy for expats to stay informed about Swedish politics.' },
		{ question: 'What Swedish cities are covered in English news?', answer: 'Nordics Today covers news from major Swedish cities including Stockholm, Gothenburg, Malmö, Uppsala, and other regions, providing comprehensive English coverage of local and national events.' },
		{ question: 'Is Swedish business news available in English?', answer: 'Yes, Nordics Today provides Swedish business news in English, covering Stockholm\'s financial sector, Volvo, Swedish startups, corporate news, and economic developments for international investors.' }
	],
	norway: [
		{ question: 'Where can I read Norwegian news in English?', answer: 'Nordics Today provides daily Norwegian news in English, covering Storting parliament, Oslo business, oil and gas industry, and maritime sector for expats and global readers.' },
		{ question: 'What is the best English news site for Norway?', answer: 'Nordics Today is a comprehensive English news aggregator for Norway, offering real-time coverage of Norwegian politics, oil and gas, shipping, and society from Oslo and across Norway.' },
		{ question: 'Does Norway have English newspapers?', answer: 'While most Norwegian newspapers publish in Norwegian, Nordics Today provides Norwegian news in English, making it accessible for expats, international residents, and English speakers worldwide.' },
		{ question: 'How can expats follow Norwegian politics in English?', answer: 'Nordics Today covers Norwegian political news in English, including Storting debates, government policy changes, and election updates, making it easy for expats to stay informed about Norwegian politics.' },
		{ question: 'What Norwegian industries are covered in English?', answer: 'Nordics Today covers Norway\'s key industries including oil and gas, shipping, maritime, renewable energy, and fishing, providing comprehensive English coverage for international professionals.' },
		{ question: 'Is Norwegian business news available in English?', answer: 'Yes, Nordics Today provides Norwegian business news in English, covering Oslo\'s financial sector, oil and gas companies, shipping industry, and economic developments for international investors.' }
	],
	denmark: [
		{ question: 'Where can I read Danish news in English?', answer: 'Nordics Today provides daily Danish news in English, covering Folketing parliament, Copenhagen business, wind energy industry, and cultural events for expats and global readers.' },
		{ question: 'What is the best English news site for Denmark?', answer: 'Nordics Today is a comprehensive English news aggregator for Denmark, offering real-time coverage of Danish politics, wind energy, green tech, and society from Copenhagen and across Denmark.' },
		{ question: 'Does Denmark have English newspapers?', answer: 'While most Danish newspapers publish in Danish, Nordics Today provides Danish news in English, making it accessible for expats, international residents, and English speakers worldwide.' },
		{ question: 'How can expats follow Danish politics in English?', answer: 'Nordics Today covers Danish political news in English, including Folketing debates, government policy changes, and election updates, making it easy for expats to stay informed about Danish politics.' },
		{ question: 'What Danish industries are covered in English?', answer: 'Nordics Today covers Denmark\'s key industries including wind energy, green technology, shipping, pharmaceuticals, and renewable energy, providing comprehensive English coverage for international professionals.' },
		{ question: 'Is Danish business news available in English?', answer: 'Yes, Nordics Today provides Danish business news in English, covering Copenhagen\'s financial sector, wind energy companies, green tech startups, and economic developments for international investors.' }
	],
	finland: [
		{ question: 'Where can I read Finnish news in English?', answer: 'Nordics Today provides daily Finnish news in English, covering Eduskunta parliament, Helsinki business, Nokia tech sector, and Arctic region news for expats and global readers.' },
		{ question: 'What is the best English news site for Finland?', answer: 'Nordics Today is a comprehensive English news aggregator for Finland, offering real-time coverage of Finnish politics, Nokia and tech industry, Arctic affairs, and society from Helsinki and across Finland.' },
		{ question: 'Does Finland have English newspapers?', answer: 'While most Finnish newspapers publish in Finnish, Nordics Today provides Finnish news in English, making it accessible for expats, international residents, and English speakers worldwide.' },
		{ question: 'How can expats follow Finnish politics in English?', answer: 'Nordics Today covers Finnish political news in English, including Eduskunta debates, government policy changes, and election updates, making it easy for expats to stay informed about Finnish politics.' },
		{ question: 'What Finnish industries are covered in English?', answer: 'Nordics Today covers Finland\'s key industries including Nokia, gaming, tech sector, Arctic affairs, and forestry, providing comprehensive English coverage for international professionals.' },
		{ question: 'Is Finnish business news available in English?', answer: 'Yes, Nordics Today provides Finnish business news in English, covering Helsinki\'s financial sector, Nokia, gaming industry, tech startups, and economic developments for international investors.' }
	],
	iceland: [
		{ question: 'Where can I read Icelandic news in English?', answer: 'Nordics Today provides daily Icelandic news in English, covering Althing parliament, Reykjavik business, volcanic activity, geothermal power, and tourism for expats and global readers.' },
		{ question: 'What is the best English news site for Iceland?', answer: 'Nordics Today is a comprehensive English news aggregator for Iceland, offering real-time coverage of Icelandic politics, volcanic activity, renewable energy, and society from Reykjavik and across Iceland.' },
		{ question: 'Does Iceland have English newspapers?', answer: 'While most Icelandic newspapers publish in Icelandic, Nordics Today provides Icelandic news in English, making it accessible for expats, international residents, and English speakers worldwide.' },
		{ question: 'How can expats follow Icelandic politics in English?', answer: 'Nordics Today covers Icelandic political news in English, including Althing debates, government policy changes, and election updates, making it easy for expats to stay informed about Icelandic politics.' },
		{ question: 'What Icelandic topics are covered in English?', answer: 'Nordics Today covers Iceland\'s unique topics including volcanic activity, geothermal power, renewable energy, tourism, fishing industry, and Arctic affairs, providing comprehensive English coverage.' },
		{ question: 'Is Icelandic business news available in English?', answer: 'Yes, Nordics Today provides Icelandic business news in English, covering Reykjavik\'s financial sector, tourism industry, renewable energy companies, and economic developments for international investors.' }
	]
};

export const COUNTRY_INTROS: Record<string, string> = {
	sweden: 'Nordics Today provides daily Swedish news in English, covering politics from the Riksdag parliament, Stockholm business updates, Volvo and tech sector, and cultural events for expats and global readers. Whether you\'re following government policy changes, tracking Swedish business developments in Gothenburg and Malmö, or staying informed about life in Sweden, our comprehensive coverage delivers real-time English news from across the country.',
	norway: 'Nordics Today provides daily Norwegian news in English, covering politics from the Storting parliament, Oslo business updates, oil and gas industry, maritime sector, and cultural events for expats and global readers. Whether you\'re following government policy changes, tracking Norway\'s energy sector developments, or staying informed about life in Norway, our comprehensive coverage delivers real-time English news from across the country.',
	denmark: 'Nordics Today provides daily Danish news in English, covering politics from the Folketing parliament, Copenhagen business updates, wind energy industry, green technology, and cultural events for expats and global readers. Whether you\'re following government policy changes, tracking Denmark\'s renewable energy developments, or staying informed about life in Denmark, our comprehensive coverage delivers real-time English news from across the country.',
	finland: 'Nordics Today provides daily Finnish news in English, covering politics from the Eduskunta parliament, Helsinki business updates, Nokia and tech sector, Arctic region news, and cultural events for expats and global readers. Whether you\'re following government policy changes, tracking Finland\'s technology developments, or staying informed about life in Finland, our comprehensive coverage delivers real-time English news from across the country.',
	iceland: 'Nordics Today provides daily Icelandic news in English, covering politics from the Althing parliament, Reykjavik business updates, volcanic activity, geothermal power, tourism, and cultural events for expats and global readers. Whether you\'re following government policy changes, tracking Iceland\'s renewable energy developments, or staying informed about life in Iceland, our comprehensive coverage delivers real-time English news from across the country.'
};
